apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-etc-pvc
  namespace: pihole
  labels:
    app: pihole
spec:
  volumeName: pihole-etc-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-config-pvc
  namespace: pihole
  labels:
    app: pihole
spec:
  volumeName: pihole-config-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi