apiVersion: v1
kind: Service
metadata:
  name: dnscrypt
spec:
  selector:
    app: dnscrypt
  ports:
    - name: dns-udp
      port: 5353
      protocol: UDP
      targetPort: 5353
    - name: dns-tcp
      port: 5353
      protocol: TCP
      targetPort: 5353
  clusterIP: 10.43.100.1
  type: LoadBalancer
